<?php

return [
    'fields' => [
        'business_name',
        'telephone',
        'email',
        'email_host',
        'website_url',
        'linkedin',
        'facebook_profile',
        'facebook_messenger',
        'instagram',
        'twitter',
        'google_rank',
        'domain_registered',
        'domain_expiry',
        'domain_nameserver',
        'domain_registrar',
        'instagram_followers',
        'instagram_follows',
        'instagram_total_photos',
        'instagram_average_likes',
        'instagram_average_comments',
        'instagram_is_verified',
        'instagram_highlight_reel_count',
        'instagram_is_biz_account',
        'instagram_account_name',
        'yelp_ads',
        'fb_messenger_ads',
        'facebook_ads',
        'instagram_ads',
        'adwords_ads',
        'gmaps_url',
        'gmb_claimed',
        'facebook_pixel',
        'google_pixel',
        'criteo_pixel',
        'google_stars',
        'google_count',
        'yelp_stars',
        'yelp_count',
        'facebook_stars',
        'facebook_count',
        'main_category',
        'address',
        'city',
        'state',
        'zip',
        'mobile_friendly',
        'google_analytics',
        'schema_markup',
        'use_wordpress',
        'use_shopify',
        'linkedin_analytics',
    ],
    // 'fields_sample' => [
    //     'first_name',
    //     'last_name',
    //     'email'
    // ]
];
